PortfolioProjectNight/Models/Skill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjectNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int SkillId { get; set; }
        public string SkillName { get; set; }
        public Nullable<byte> Rate { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

PortfolioProjectNight/Controllers/SkillController.cs
using PortfolioProjectNight.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.Collections;
using System.Web.Helpers;


namespace PortfolioProjectNight.Controllers
{
    public class SkillController : Controller
    {

        DbMyPortfolioNightEntities context = new DbMyPortfolioNightEntities();

        public ActionResult SkillList(int page = 1)
        {
            var values = context.Skill.ToList().ToPagedList(page, 5);
            return View(values);
        }

        [HttpGet]
        public ActionResult CreateSkill()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSkill(Skill skill)
        {
            context.Skill.Add(skill);
            context.SaveChanges();
            return RedirectToAction("SkillList");
        }

        public ActionResult DeleteSkill(int id)
        {
            var value = context.Skill.Find(id);
            context.Skill.Remove(value);
            context.SaveChanges();
            return RedirectToAction("SkillList");
        }

        [HttpGet]
        public ActionResult UpdateSkill(int id)
        {
            var value = context.Skill.Find(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult UpdateSkill(Skill skill)
        {
            var value = context.Skill.Find(skill.SkillId);
            value.SkillName = skill.SkillName;
            value.Rate = skill.Rate;
            context.SaveChanges();
            return RedirectToAction("SkillList");
        }

        public ActionResult SkillsGraphic()
        {
            return Json(SkillGraphicStatistic(), JsonRequestBehavior.AllowGet);
        }

        public List<Models.Skill> SkillGraphicStatistic()
        {
            List<Models.Skill> GraphicSkillList = new List<Models.Skill>();
            GraphicSkillList = context.Skill.Select(x => new Models.Skill
            {
                SkillName = x.SkillName,
                Rate = x.Rate
            }).ToList();
            return GraphicSkillList;
        }

        public ActionResult SkillStatisticIndex()
        {
            var values = context.Skill.ToList();
            return View(values);
        }

        public ActionResult SkillStatisticGraphic2()
        {
            ArrayList xvalue = new ArrayList();
            ArrayList yvalue = new ArrayList();
            var values = context.Skill.ToList();
            values.ToList().ForEach(x => xvalue.Add(x.SkillName));
            values.ToList().ForEach(y => yvalue.Add(y.Rate));
            var graphic = new Chart(width: 1000, height: 500).AddTitle("Yetenekler").AddSeries(chartType: "Column", name: "Yetenek", xValue: xvalue, yValues: yvalue);
            return File(graphic.ToWebImage().GetBytes(), "image/jpeg");
        }
    }
}

PortfolioProjectNight/Views/Skill/CreateSkill.cshtml
@{
    ViewBag.Title = "CreateSkill";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2 class="mb-4">Yetenek Oluşturma Sayfası</h2>


<form method="post">

    <label>Yetenek Başlığı</label>
    <input type="text" name="SkillName" value="" class="form-control" />
    <br />

    <label>Yetenek Değeri</label>
    <input type="number" name="Rate" value="" class="form-control" />
    <br />

    <button class="btn btn-warning">Yetenek Ekle</button>

</form>

PortfolioProjectNight/Views/Skill/SkillList.cshtml
@model PagedList.IPagedList<PortfolioProjectNight.Models.Skill>
@using PagedList
@using PagedList.Mvc

@*@model List<PortfolioProjectNight.Models.Skill>*@

@{
    ViewBag.Title = "SkillList";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2 class="mb-4">Yetenek Listesi ve İşlemleri</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Değer</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SkillId</td>
            <td>@item.SkillName</td>
            <td>@item.Rate</td>
            <td><a href="/Skill/DeleteSkill/@item.SkillId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Skill/UpdateSkill/@item.SkillId" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, page => Url.Action("SkillList", new { page }), new PagedListRenderOptions
{
    LiElementClasses = new List<string>
    { "page-link"}
})

<a href="/Skill/CreateSkill" class="btn btn-primary">Yeni Yetenek Girişi</a>

PortfolioProjectNight/Views/Skill/SkillStatisticGraphic2.cshtml
@{
    ViewBag.Title = "SkillStatisticGraphic2";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>SkillStatisticGraphic2</h2>

<img src="@Url.Action("SkillStatisticGraphic2","Skill")" />

PortfolioProjectNight/Views/Skill/SkillStatisticIndex.cshtml
@model IEnumerable<PortfolioProjectNight.Models.Skill>

@{
    ViewBag.Title = "SkillStatisticIndex";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yetenek Grafiği</h2>

<!DOCTYPE html>
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<body>

    <canvas id="myChart" style="width:100%;max-width:600px"></canvas>

    <script>
        const xValues = ["Italy", "France", "Spain", "USA", "Argentina"];
        const yValues = [55, 49, 44, 24, 15];
        const barColors = [
            "#b91d47",
            "#00aba9",
            "#2b5797",
            "#e8c3b9",
            "#1e7145"
        ];

        new Chart("myChart", {
            type: "doughnut",
            data: {
                labels: xValues,
                datasets: [{
                    backgroundColor: barColors,
                    data: yValues
                }]
            },
            options: {
                title: {
                    display: true,
                    text: "World Wide Wine Production 2018"
                }
            }
        });
    </script>

</body>
</html>

PortfolioProjectNight/Views/Skill/UpdateSkill.cshtml
@model PortfolioProjectNight.Models.Skill

@{
    ViewBag.Title = "UpdateSkill";
    Layout = "~/Views/Admin/Index.cshtml";
}

<h2>Yetenek Güncelleme Sayfası</h2>

<form method="post">


    <label style="display:none">Yetenek ID</label>
    @Html.TextBoxFor(x => x.SkillId, new { @class = "form-control", @readonly = "readonly", @style = "display:none" })
    <br />

    <label>Yetenek Başlığı</label>
    @Html.TextBoxFor(x => x.SkillName, new { @class = "form-control" })
    <br />

    <label>Yetenek Değeri</label>
    @Html.TextBoxFor(x => x.Rate, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Yetenek Güncelle</button>

</form>